Ci/setup base worflows
okp4/github_exporter pull request #3
Opened 2022-10-14 08:41 UTC by hleonardtek

2022-10-20 08:57 UTC, ccamel commented
@amimart @ad2ien  @hleonardtek FYI, I configured the branch protection rule for `main`, in the same way as we do for all our other opensource projects.

2022-10-24 15:16 UTC, amimart approved these changes
Very nice thank you ! 😎

2022-10-24 15:38 UTC, ccamel requested changes

2022-10-24 15:38 UTC, ccamel commented on .golangci.yml
> +  #     - "this line is used by starport scaffolding .*"
[Please, don't commit commented out code](https://kentcdodds.com/blog/please-dont-commit-commented-out-code).

To be applied everwhere relevent in this PR. :wink:

2022-10-24 15:38 UTC, ccamel commented on README.md
> +[![License](https://img.shields.io/badge/License-BSD_3--Clause-blue.svg?style=for-the-badge)](https://opensource.org/licenses/BSD-3-Clause)
Not correct. The license is MIT, as stated by the [LICENSE](https://github.com/okp4/github-exporter/blob/main/LICENSE) file. Moreover, this license should be amended to (1) state the copyright to the source and (2) express the terms for use of the software.

2022-10-24 15:38 UTC, ccamel commented on .github/workflows/build.yml
> +    runs-on: ubuntu-20.04
Update running images to latest: `ubuntu-22.04`

2022-10-24 15:38 UTC, ccamel commented on .github/workflows/build.yml
> +          go-version: "^1.14"
Please update go version to latest one: `1.19`.

2022-10-24 15:38 UTC, ad2ien approved these changes
@hleonardtek, I added a few commits to add some consistency. 
Ok to activate some disabled linters in the future 😜

2022-10-24 15:58 UTC, ad2ien commented on .github/workflows/build.yml
> +    runs-on: ubuntu-20.04
done

2022-10-24 16:00 UTC, ad2ien commented on README.md
> +[![License](https://img.shields.io/badge/License-BSD_3--Clause-blue.svg?style=for-the-badge)](https://opensource.org/licenses/BSD-3-Clause)
I mentioned the previous license and the original project at the beginning of the readme, and set the licence to BSD.

2022-10-24 16:15 UTC, hleonardtek commented
Perfect, thank you :blush:  :+1:

2022-10-25 06:24 UTC, ad2ien commented on .github/workflows/build.yml
> +          go-version: "^1.14"
yes, done!

2022-10-26 09:03 UTC, ad2ien approved these changes
:clap:

2022-10-31 14:10 UTC, ad2ien commented
@ccamel thanks we took your remarks into account. Is it ok to merge?

2022-10-31 14:32 UTC, ccamel approved these changes
:+1:

2022-10-31 14:35 UTC, merged